
### Raiz da API
GET http://localhost:5091


# FUNCIONÁRIO ######################################

### Criação de um novo funcionário
POST http://localhost:5091/funcionario/cadastrar
Content-Type: application/json

{
    "nome": "Miguel Viapiana Jung",
    "cpf" : "09608709970"
}

### Obtenção de todos os funcionários
GET  http://localhost:5091/funcionario/listar
# FOLHA ############################################

### Criação de uma nova folha
POST http://localhost:5091/folha/cadastrar/
Content-Type: application/json

{
    "valor": 20,
    "quantidade" : 120,
    "mes" : 10,
    "ano" : 2023,
    "funcId" : "90592f7c-0c0a-4030-a493-2bf1f776a03f"

}

### Obtenção de todas as folhas
GET  http://localhost:5091/folha/listar

### Obtenção de uma folha
GET http://localhost:5091/folha/buscar/10/2023