// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Miguel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240502140300_Criacao")]
    partial class Criacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Arnaldo.Miguel.Models.Folha", b =>
                {
                    b.Property<string>("folhaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuncId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantidade")
                        .HasColumnType("REAL");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.Property<string>("funcionarioId")
                        .HasColumnType("TEXT");

                    b.Property<double>("impostoFgts")
                        .HasColumnType("REAL");

                    b.Property<double>("impostoInss")
                        .HasColumnType("REAL");

                    b.Property<double>("impostoIrrf")
                        .HasColumnType("REAL");

                    b.Property<double>("salarioBruto")
                        .HasColumnType("REAL");

                    b.Property<double>("salarioLiquido")
                        .HasColumnType("REAL");

                    b.HasKey("folhaId");


                    b.ToTable("Folhas");
                });

            modelBuilder.Entity("Arnaldo.Miguel.Models.Funcionario", b =>
                {
                    b.Property<string>("funcionarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("funcionarioId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Arnaldo.Miguel.Models.Folha", b =>
                {
                    b.HasOne("Arnaldo.Miguel.Models.Funcionario", "funcionario")
                        .WithMany("Folhas")
                        .HasForeignKey("funcionarioId");

                    b.Navigation("funcionario");
                });

            modelBuilder.Entity("Arnaldo.Miguel.Models.Funcionario", b =>
                {
                    b.Navigation("Folhas");
                });
#pragma warning restore 612, 618
        }
    }
}
